import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from 'next/image'

const Home: NextPage = () => {
  const routines = api.exercise.get.useQuery();
  console.log(routines.data)

  return (
    <>
      <Head>
        <title>Routine App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex bg-dark-blue h-screen ">
        <div className="w-4/5 mx-auto ">
          <h1 className="text-white font-semibold text-3xl py-4">Make yours routines</h1>
          <picture className='my-2'>
            <Image className="rounded-xl" src={"/running.jpg"} alt="Picture of a man doing workout" width={380} height={400} />
          </picture>
          <p className='text-gray-400 my-3 w-96 text-center text-sm'>Make your own workout routines and define how and when do it.</p>
          <button className="py-2.5 text-white bg-blue-600 rounded-full my-3 w-32 font-semibold hover:bg-blue-700">Join</button>
        </div>
      </main>
    </>
  );
};

export default Home;


