import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from 'next/image'

const Home: NextPage = () => {
  const routines = api.exercise.get.useQuery();
  console.log(routines.data)

  return (
    <>
      <Head>
        <title>Routine App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex bg-slate-600 h-screen ">
        <div className="w-4/5 mx-auto py-5">
          <picture className="opacity-50">
            <Image src={"/running.jpg"} alt="Picture of a man doing workout" width={400} height={400} />
          </picture>
        </div>
      </main>
    </>
  );
};

export default Home;
