import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'
import { PropsWithChildren } from 'react'

export default function Layout({ children }: PropsWithChildren) {
    return (
        <>
            <Head>
                <title>Workout App</title>
                <meta name="description" content="Fullstack App generated by create-t3-app, with responsive design." />
                <meta name="keywords" content="Fullstack, React, TRPC, Typescript" />
                <meta name="author" content="Nicolas Bouffanais Lay" />
                <meta name="robots" content="index" />
                <meta name="robots" content="follow" />
                <meta httpEquiv="Cache-Control" content="no-store" />
                <meta charSet="utf-8" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="theme-color" content="#0064b6" />
            </Head>
            <Navbar />
            <main>{children}</main>
            <Footer />
        </>
    )
}